### ISSUE TITLE
Our.Umbraco.Vorto.Web.PropertyEditors.VortoPropertyEditor+VortoPropertyValueEditor - Error converting DB value to String

### ISSUE THREAD

**Issue by arlan85** [umco/umbraco-vorto#104] opened 2018-06-02 15:38 UTC
Hi, I'm getting this issue a long time ago on my site and I did not found what is the cause of it or how to fix it.This issue happens many times on a regular day. 

From App Insights:
```
Exception: Exception while creating a value.
  Module "Umbraco.Core.Cache.HttpRuntimeCacheProvider", line 286, col 0, in GetCacheItem
    System.Object GetCacheItem(System.String, System.Func`1[System.Object], System.Nullable`1[System.TimeSpan], Boolean, System.Web.Caching.CacheItemPriority, System.Web.Caching.CacheItemRemovedCallback, System.Web.Caching.CacheDependency)
  Module "Umbraco.Core.Cache.HttpRuntimeCacheProvider", line 0, col 0, in GetCacheItem
    System.Object GetCacheItem(System.String, System.Func`1[System.Object])
  Module "Umbraco.Core.Cache.DeepCloneRuntimeCacheProvider", line 32, col 0, in GetCacheItem
    System.Object GetCacheItem(System.String, System.Func`1[System.Object])
  Module "Our.Umbraco.Vorto.Helpers.VortoHelper", line 61, col 0, in GetTargetDataTypeDefinition
    Umbraco.Core.Models.IDataTypeDefinition GetTargetDataTypeDefinition(System.Guid)
  Module "Our.Umbraco.Vorto.Web.PropertyEditors.VortoPropertyEditor+VortoPropertyValueEditor", line 44, col 0, in ConvertDbToString
    System.String ConvertDbToString(Umbraco.Core.Models.Property, Umbraco.Core.Models.PropertyType, Umbraco.Core.Services.IDataTypeService)
NullReferenceException: Object reference not set to an instance of an object.
  Module "Our.Umbraco.Vorto.Helpers.VortoHelper+<>c__DisplayClass1", line 0, col 0, in GetTargetDataTypeDefinition { <lambda> }
    System.Object <GetTargetDataTypeDefinition>b__0()
  Module "Umbraco.Core.Cache.DictionaryCacheProviderBase+<>c__DisplayClass1", line 0, col 0, in GetSafeLazy { <lambda> }
    System.Object <GetSafeLazy>b__0()

```
I get this on logs:
```
ERROR Our.Umbraco.Vorto.Web.PropertyEditors.VortoPropertyEditor+VortoPropertyValueEditor - Error converting DB value to String
System.Exception: Exception while creating a value. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Our.Umbraco.Vorto.Helpers.VortoHelper.<>c__DisplayClass1.<GetTargetDataTypeDefinition>b__0()
   at Umbraco.Core.Cache.DictionaryCacheProviderBase.<>c__DisplayClass1.<GetSafeLazy>b__0()
   --- End of inner exception stack trace ---
   at Umbraco.Core.Cache.HttpRuntimeCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, CacheDependency dependency)
   at Umbraco.Core.Cache.HttpRuntimeCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at Umbraco.Core.Cache.DeepCloneRuntimeCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at Our.Umbraco.Vorto.Helpers.VortoHelper.GetTargetDataTypeDefinition(Guid myId)
   at Our.Umbraco.Vorto.Web.PropertyEditors.VortoPropertyEditor.VortoPropertyValueEditor.ConvertDbToString(Property property, PropertyType propertyType, IDataTypeService dataTypeService)

```
I'm using Umbraco 7.6.3
Vorto 1.5.3
Hosted on Azure.

Any help would be appreciated.
Arlan

**Comment by mattbrailsford** [comment] 2018-08-29 09:31
I can't say I know what the issue is, but I've tried putting some null checks in that area in commit  5f39ad7 so hopefully once the next release is out we can try and narrow it down. There shouldn't really be anything that is null in that area, but clearly something is.

**Comment by arlan85** [comment] 2018-09-05 19:18
@mattbrailsford looking into end to end transaction I realize that most of this exceptions happens when this happens first:

`Failed to load Xml from file. System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\local\Temp\UmbracoXml\106f53b4d5b2ac8395dfe8c8a5af11b26f7c0af3\umbraco.config'. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) at umbraco.content.LoadXmlFromFile()`

This also happens when azure move the website from a pool to another or the server uses scalability features. 
I hope attached info could make more clear the issue.
Thank you.

**Comment by cmwalolo** [comment] 2018-11-30 10:09
Any timing idea for the new version that fixes this ?

**Comment by mattbrailsford** [comment] 2018-11-30 10:47
Hi @cmwalolo, not currently so if you need this fix, your best bet is to run a custom build of the current source.

@arlan85 looking at the log you posted in Sep (sorry for the late reply), have you read the guidelines regarding configuring the XML Cache to be stored in local temp on Azure? https://our.umbraco.com/documentation/getting-started/setup/server-setup/azure-web-apps#umbraco-xml-cache-file-and-other-temp-files

**Comment by mattbrailsford** [comment] 2018-12-13 16:53
Closing as new release coming out shortly, and I believe the issue is more an Azure configuration issue. Feel free to re-open if you have any further information to suggest otherwise.

**Closed by mattbrailsford** 2018-12-13 16:53 UTC

**Comment by cmwalolo** [comment] 2018-12-13 16:57
Ok, let me check when that version is out. It's not azure related this instance with all those error messages is not ruinning on azure./ Thank you
